version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 3002:5432
  app:
    container_name: app
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db
      DB_PORT: 5432
      APP_PORT: 3000
    volumes:
      - .:/app
